apiVersion: v1
kind: Pod
metadata:
  name: vault-kubernetes-kms
  namespace: kube-system
spec:
  containers:
    - name: vault-kubernetes-kms
      image: falcosuessgott/vault-kubernetes-kms:v0.0.3
      command:
        - /vault-kubernetes-kms
        - --vault-address=https://host.minikube.internal
        - --socket=unix:///opt/kms/vaultkms.socket
        - --vault-k8s-mount=minikube-cluster
        - --vault-k8s-role=kms
      env:
        # add vaults CA file via env vars
        - name: VAULT_CACERT
          value: /opt/ca/ca.crt
      volumeMounts:
        # mount the hostpath volume to enable the kms socket to the node
        - name: kms
          mountPath: /opt/kms
        # mount the ca cert under /opt/ca.crt
        - name: ca-cert
          mountPath: /opt/ca/ca.crt
          subPath: ca.crt
  volumes:
    - name: kms
      hostPath:
        path: /opt/kms
    - name: ca-cert
      secret:
        secretName: ca-cert
        items:
          - key: ca.crt
            path: ca.crt
