apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-csi
  namespace: csi
spec:
  provider: vault
  parameters:
    vaultAddress: https://host.minikube.internal
    vaultKubernetesMountPath: minikube-cluster
    vaultCACertPath: /opt/ca.crt
    roleName: csi
    objects: |
      - objectName: "password"
        secretPath: "csi/data/secrets"
        secretKey: "password"
      - objectName: "username"
        secretPath: "csi/data/secrets"
        secretKey: "username"
  secretObjects:
    - data:
      - key: username
        objectName: username
      secretName: csi-secret
      type: Opaque
