apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vso-vault-static-secret
  namespace: vso
spec:
  type: kv-v2
  mount: vso
  path: secrets
  destination:
    name: vso-secret
    create: true
  refreshAfter: 30s
  vaultAuthRef: vso-vault-auth
