site_name: HashiCorp Vault Playground
site_description: Bootstrap a Vault HA Cluster locally including TLS, Unsealing, HAProxy, Minikube in less than a minute!
site_author: FalcoSuessgott

repo_name: FalcoSuessgott/hashicorp-vault-playground
repo_url: https://github.com/FalcoSuessgott/hashicorp-vault-playground

docs_dir: docs/

plugins:
  - search
  - git-authors
  - git-revision-date-localized:
      locale: en
      enable_creation_date: false

nav:
  - Home: home.md
  - Quickstart: quickstart.md
  - Labs:
    - Vault:
      - Vault HA Cluster: vault.md
      - TLS: tls.md
      - Generate Root: generate-root.md
      - Rekeying: rekey.md
      - Seal & Unsealing: seal.md
      - HAProxy: haproxy.md
    - Kubernetes:
      - Minikube: minikube.md
      - KMS: kms.md
      - External Secrets Manager: esm.md
      - Vault Secrets Operator: vso.md
      - Vault Agent Injector: vai.md
      - Secret Store CSI Driver: csi.md
      - Cert Manager: cm.md
    - Dynamic DB Credentials:
      - MySQL: databases.md
    - Boundary:
      - Kubernetes Cluster Access: boundary.md
  - Troubleshooting:
    - troubleshooting.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - admonition
  - def_list
  - footnotes
  - attr_list
  - md_in_html
  - tables
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

theme:
  icon:
    edit: material/pencil
    view: material/eye
    repo: fontawesome/brands/github
  name: material
  favicon: assets/favicon.ico
  #logo: assets/logo.png
  language: en
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/eye
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/eye-outline
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - content.code.copy
    - content.action.edit
    - navigation.top
    - navigation.expand
    - navigation.footer
