apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret
  namespace: esm
spec:
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  refreshInterval: "1h"
  target:
    name: esm-secret

  data:
%{ for secret in secrets ~}
    - secretKey: ${secret.name}
      remoteRef:
        key: ${secret.path}
        property: ${secret.name}
%{ endfor }
