apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secret-store
  namespace: esm
spec:
  provider:
    vault:
      server: https://host.minikube.internal
      caBundle: ${ca}
      auth:
        kubernetes:
          mountPath: minikube-cluster
          role: esm
          serviceAccountRef:
            name: esm-external-secrets
          secretRef:
            name: esm-external-secrets-token-vxnlq
            key: token
  retrySettings:
    maxRetries: 5
    retryInterval: 10s
